language: python

sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"

cache:
  directories:
    - $HOME/.pip-cache/

install:
  - pip install --upgrade pip
  - pip install -e . --cache-dir $HOME/.pip-cache

script:
  - py.test